---
driver_plugin: ec2
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: patcon-macbook
  ssh_key: <%= File.expand_path('~/.ssh/id_rsa') %>
  availability_zone: us-east-1d
  require_chef_omnibus: 11.4.4

platforms:
- name: ubuntu-12.04
  driver_config:
    image_id: ami-fd20ad94
    username: ubuntu
- name: centos-6.3
  driver_config:
    image_id: ami-ef5ff086
    username: ec2-user

suites:
- name: default
  run_list: ["role[base]"]
  attributes: {}
