---
driver_plugin: ec2
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  flavor_id: t1.micro
  aws_ssh_key_id: vagrant
  ssh_key: <%= File.expand_path('./../keys/vagrant') %>
  availability_zone: us-east-1d
  require_chef_omnibus: 11.4.4

platforms:
# Source: http://cloud-images.ubuntu.com/locator/ec2/
- name: precise64
  driver_config:
    image_id: ami-e7582d8e
    username: ubuntu
# Source: http://wiki.centos.org/Cloud/AWS
- name: centos6-64
  driver_config:
    image_id: ami-8a8932e3
    username: ec2-user

suites:
- name: default
  run_list: ["role[base]"]
  attributes: {}
