#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'base',
  :path => 'cookbooks-source/base'
cookbook 'fail2ban'
cookbook 'git'
cookbook 'openssh'
cookbook 'unattended-upgrades',
  :git => "https://github.com/firstbanco/chef-unattended-upgrades"
cookbook 'vim'
cookbook 'yum',
  # Pending PR: https://github.com/opscode-cookbooks/yum/pull/49
  :git => 'https://github.com/patcon/yum',
  :ref => 'COOK-3145-better-epel-key-url'
cookbook 'zsh'
